title: AI based Portfolio optimizer
url: "https://www.gendriven.com"
baseurl:
author: gendriven
email: tillhoffmann@gmail.com
description: >-
  gendriven is an AI based calculator to optimize Portfolios

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

github:
  source:
    branch: production

# Google Analytics
google_analytics: G-3XF21G6V7L

plugins:
  - jekyll-feed
