title: AI based Portfolio optimizer
url: "https://gendriven.github.io/gendriven-website"
baseurl:
author: gendriven
email: tillhoffmann@gmail.com
description: >-
  gendriven is an AI based calculator to optimize Portfolios

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

github:
  source:
    branch: production

plugins:
  - jekyll-feed
