title: AI based Portfolio optimizer
url: "https://portfoio.github.io/portfoio-website"
baseurl:
author: Portfoio
email: tillhoffmann@gmail.com
description: >-
  Portfoio is an AI based calculator to optimize Portfolios

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

github:
  source:
    branch: production

plugins:
  - jekyll-feed
